name: plugins
description: Send a message to whatsapp without save the contact number.
version: 0.0.1
homepage: https://github.com/anilgsharma900/direct_whatsapp_chat

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.plugins
        pluginClass: PluginsPlugin
      ios:
        pluginClass: PluginsPlugin
